import { StyleSheet } from 'react-native';
import type { ColorTokens } from '@/src/theme';

export function makeStyles(colors: ColorTokens) {
  return StyleSheet.create({
    screen: { backgroundColor: colors.linen, flex: 1 },
    content: { padding: 24, paddingBottom: 36 },
    back: { minHeight: 44, justifyContent: 'center' },
    backText: { color: colors.spruce, fontWeight: '800' },
    kicker: {
      color: colors.clay,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1.4,
      marginTop: 14,
    },
    title: { color: colors.ink, fontSize: 32, fontWeight: '700', marginTop: 7 },
    intro: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: 8 },
    themeCard: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: 20,
      padding: 14,
    },
    themeTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' },
    themeSwitch: {
      backgroundColor: colors.linenMuted,
      borderRadius: 12,
      flexDirection: 'row',
      marginTop: 10,
      padding: 3,
    },
    themeOption: {
      alignItems: 'center',
      borderRadius: 9,
      flex: 1,
      minHeight: 38,
      justifyContent: 'center',
    },
    themeOptionActive: { backgroundColor: colors.white },
    themeOptionText: { color: colors.muted, fontSize: 13, fontWeight: '800' },
    themeOptionTextActive: { color: colors.spruce },
    devicesCard: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: 14,
      padding: 14,
    },
    devicesTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' },
    devicesIntro: { color: colors.muted, lineHeight: 19, marginTop: 5 },
    deviceRow: {
      alignItems: 'center',
      borderTopColor: colors.border,
      borderTopWidth: 1,
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'space-between',
      marginTop: 12,
      paddingTop: 12,
    },
    deviceCopy: { flex: 1 },
    deviceName: { color: colors.ink, fontWeight: '800' },
    deviceMeta: { color: colors.muted, fontSize: 12, marginTop: 3 },
    revoke: { minHeight: 38, justifyContent: 'center', paddingHorizontal: 8 },
    revokeText: { color: colors.berry, fontSize: 12, fontWeight: '800' },
    memoryButton: {
      backgroundColor: colors.white,
      borderColor: colors.spruce,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: 14,
      padding: 16,
    },
    memoryButtonTitle: { color: colors.ink, fontWeight: '800' },
    memoryButtonText: { color: colors.muted, lineHeight: 20, marginTop: 5 },
    loader: { marginTop: 30 },
    alert: {
      backgroundColor: colors.berrySoft,
      borderColor: colors.berry,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: 18,
      padding: 14,
    },
    alertTitle: { color: colors.ink, fontWeight: '800' },
    alertText: { color: colors.muted, lineHeight: 19, marginTop: 5 },
    retry: { alignSelf: 'flex-start', minHeight: 36, justifyContent: 'center', marginTop: 6 },
    retryText: { color: colors.spruce, fontWeight: '800' },
    form: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderLeftColor: colors.spruce,
      borderLeftWidth: 4,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: 20,
      padding: 16,
    },
    label: { color: colors.ink, fontSize: 14, fontWeight: '800', marginTop: 12 },
    input: {
      backgroundColor: colors.linen,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      color: colors.ink,
      fontSize: 16,
      marginTop: 7,
      minHeight: 48,
      paddingHorizontal: 12,
    },
    readonly: { color: colors.muted, marginTop: 7 },
    help: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 16 },
    error: { color: colors.berry, marginTop: 12 },
    primary: {
      alignItems: 'center',
      backgroundColor: colors.spruce,
      borderRadius: 16,
      justifyContent: 'center',
      marginTop: 18,
      minHeight: 50,
    },
    primaryText: { color: colors.white, fontWeight: '800' },
    signOut: {
      alignItems: 'center',
      borderColor: colors.berry,
      borderRadius: 16,
      borderWidth: 1,
      justifyContent: 'center',
      marginTop: 28,
      minHeight: 50,
    },
    signOutText: { color: colors.berry, fontWeight: '800' },
    disabled: { opacity: 0.6 },
  });
}

export type ProfileStyles = ReturnType<typeof makeStyles>;
