import { StyleSheet } from 'react-native';

import { darkTheme, subtleBackground, type ColorTokens } from '@/src/theme';

export function makeStyles(colors: ColorTokens, mode: 'light' | 'dark') {
  return StyleSheet.create({
    screen: { ...subtleBackground(colors), flex: 1 },
    flex: { flex: 1 },
    header: {
      alignItems: 'center',
      backgroundColor: colors.white,
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      gap: 11,
      minHeight: 66,
      paddingHorizontal: darkTheme.spacing.content,
      paddingVertical: 9,
    },
    back: { alignItems: 'center', justifyContent: 'center', height: 44, width: 32 },
    backIcon: { color: colors.ink, fontFamily: 'MaterialSymbols_400Regular', fontSize: 24 },
    avatar: {
      alignItems: 'center',
      backgroundColor: colors.spruceSoft,
      borderRadius: 18,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    avatarText: { color: colors.spruceOn, fontSize: 16, fontWeight: '700' },
    headerTitles: { flex: 1, justifyContent: 'center' },
    title: { color: colors.ink, fontSize: 17, fontWeight: '700' },
    headerSubtitle: { color: colors.muted, fontSize: 12, marginTop: 2 },
    typingLabel: { color: colors.spruce, fontSize: 12, fontWeight: '600', marginTop: 2 },
    loader: { marginTop: 40 },
    error: {
      backgroundColor: colors.berrySoft,
      borderRadius: darkTheme.radius.input,
      color: colors.berry,
      margin: darkTheme.spacing.screen,
      padding: 12,
    },
    messages: {
      flexGrow: 1,
      gap: 9,
      paddingHorizontal: darkTheme.spacing.content,
      paddingTop: 20,
      paddingBottom: 24,
    },
    emptyCard: { alignItems: 'center', alignSelf: 'center', marginTop: 80, maxWidth: 260 },
    emptyIcon: {
      color: colors.spruce,
      fontFamily: 'MaterialSymbols_400Regular',
      fontSize: 34,
      marginBottom: 12,
    },
    emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: '700', textAlign: 'center' },
    empty: { color: colors.muted, lineHeight: 20, marginTop: 6, textAlign: 'center' },
    messageRow: { alignItems: 'flex-end', flexDirection: 'row', gap: 6 },
    mineRow: { justifyContent: 'flex-end' },
    message: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      maxWidth: '82%',
      paddingHorizontal: 13,
      paddingVertical: 10,
    },
    theirs: { borderBottomLeftRadius: 5 },
    mine: {
      backgroundColor: colors.spruce,
      borderColor: colors.spruce,
      borderBottomRightRadius: 5,
    },
    messageText: { color: colors.ink, fontSize: 16, lineHeight: 22 },
    mineText: { color: mode === 'dark' ? '#111322' : '#FFFFFF' },
    meta: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end', marginTop: 5 },
    metaText: { color: colors.muted, fontSize: 11 },
    mineMeta: { color: mode === 'dark' ? '#111322' : '#FFFFFF' },
    status: { marginLeft: 8 },
    sentCheck: {
      fontFamily: 'MaterialSymbols_400Regular',
      fontSize: 17,
      lineHeight: 18,
      marginLeft: 7,
    },
    recipientAvatar: {
      alignItems: 'center',
      backgroundColor: colors.spruceSoft,
      borderColor: colors.spruce,
      borderRadius: 12,
      borderWidth: 1,
      height: 24,
      justifyContent: 'center',
      marginBottom: 2,
      width: 24,
    },
    recipientInitial: { color: colors.spruceOn, fontSize: 11, fontWeight: '700' },
    failedAction: { alignItems: 'center', flexDirection: 'row', marginLeft: 8, minHeight: 28 },
    failedIcon: {
      color: mode === 'dark' ? '#111322' : '#FFFFFF',
      fontFamily: 'MaterialSymbols_400Regular',
      fontSize: 15,
    },
    failedText: {
      color: mode === 'dark' ? '#111322' : '#FFFFFF',
      fontSize: 11,
      fontWeight: '700',
      marginLeft: 3,
      textDecorationLine: 'underline',
    },
    typingBubble: {
      alignSelf: 'flex-start',
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 17,
      borderBottomLeftRadius: 5,
      borderWidth: 1,
      paddingHorizontal: 15,
      paddingVertical: 10,
    },
    typingDots: { color: colors.muted, fontSize: 10, letterSpacing: 2 },
    composer: {
      backgroundColor: 'transparent',
      paddingHorizontal: darkTheme.spacing.content,
      paddingTop: 6,
    },
    composerError: { color: colors.berry, fontSize: 13, marginBottom: 7 },
    composerRow: {
      alignItems: 'flex-end',
      backgroundColor: 'transparent',
      flexDirection: 'row',
      gap: 8,
    },
    voicePanel: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      marginBottom: 9,
      padding: 12,
    },
    voiceStatus: { alignItems: 'center', flexDirection: 'row', gap: 8 },
    recordDot: { backgroundColor: colors.berry, borderRadius: 5, height: 9, width: 9 },
    recordDotSaved: { backgroundColor: colors.spruce },
    voiceText: { color: colors.ink, flex: 1, fontSize: 13, fontWeight: '600' },
    voiceTime: { color: colors.muted, fontSize: 12, fontVariant: ['tabular-nums'] },
    voiceActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 9,
      justifyContent: 'flex-end',
      marginTop: 10,
    },
    voiceAction: {
      alignItems: 'center',
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      height: 40,
      justifyContent: 'center',
      width: 44,
    },
    voiceActionWide: {
      alignItems: 'center',
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 5,
      height: 40,
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    voiceActionIcon: { color: colors.ink, fontFamily: 'MaterialSymbols_400Regular', fontSize: 20 },
    voiceActionText: { color: colors.ink, fontSize: 13, fontWeight: '600' },
    voicePrimary: {
      alignItems: 'center',
      backgroundColor: colors.spruce,
      borderRadius: 12,
      height: 40,
      justifyContent: 'center',
      paddingHorizontal: 17,
    },
    voicePrimaryText: {
      color: mode === 'dark' ? colors.linen : '#FFFFFF',
      fontSize: 13,
      fontWeight: '700',
    },
    voiceHint: { color: colors.muted, fontSize: 11, marginTop: 9 },
    composerInput: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 22,
      borderWidth: 1,
      color: colors.ink,
      elevation: 3,
      flex: 1,
      fontSize: 15,
      maxHeight: 110,
      minHeight: 44,
      paddingHorizontal: 15,
      paddingVertical: 8,
      shadowColor: '#000000',
      shadowOffset: { height: 2, width: 0 },
      shadowOpacity: 0.12,
      shadowRadius: 5,
    },
    send: {
      alignItems: 'center',
      backgroundColor: colors.spruce,
      borderRadius: 22,
      elevation: 3,
      height: 44,
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { height: 2, width: 0 },
      shadowOpacity: 0.16,
      shadowRadius: 5,
      width: 44,
    },
    sendDisabled: { opacity: 0.45 },
    mic: {
      alignItems: 'center',
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 22,
      borderWidth: 1,
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    micRecording: { backgroundColor: colors.berrySoft, borderColor: colors.berry },
    micIcon: { color: colors.spruce, fontFamily: 'MaterialSymbols_400Regular', fontSize: 22 },
    micRecordingIcon: { color: colors.berry },
    sendIcon: {
      color: mode === 'dark' ? colors.linen : '#FFFFFF',
      fontFamily: 'MaterialSymbols_400Regular',
      fontSize: 23,
      lineHeight: 25,
    },
  });
}
