import { StyleSheet } from 'react-native';

import { darkTheme, subtleBackground, type ColorTokens } from '@/src/theme';

export function makeStyles(colors: ColorTokens, mode: 'light' | 'dark') {
  return StyleSheet.create({
    screen: { ...subtleBackground(colors), flex: 1 },
    flex: { flex: 1 },
    header: {
      alignItems: 'center',
      backgroundColor: colors.white,
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      gap: 11,
      minHeight: 66,
      paddingHorizontal: darkTheme.spacing.content,
      paddingVertical: 9,
    },
    content: {
      flexGrow: 1,
      padding: darkTheme.spacing.content,
      paddingBottom: 18,
    },
    back: { alignItems: 'center', justifyContent: 'center', height: 44, width: 32 },
    backIcon: { color: colors.ink, fontFamily: 'MaterialSymbols_400Regular', fontSize: 24 },
    title: {
      color: colors.ink,
      flex: 1,
      fontSize: 17,
      fontWeight: '700',
    },
    modelBar: {
      alignItems: 'center',
      backgroundColor: colors.white,
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      gap: 10,
      minHeight: 54,
      paddingHorizontal: darkTheme.spacing.content,
      zIndex: 5,
    },
    modelLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' },
    modelButton: {
      alignItems: 'center',
      borderColor: colors.border,
      borderRadius: 10,
      borderWidth: 1,
      flex: 1,
      flexDirection: 'row',
      gap: 6,
      justifyContent: 'space-between',
      minHeight: 38,
      paddingHorizontal: 10,
    },
    modelButtonText: { color: colors.ink, flex: 1, fontSize: 13, fontWeight: '700' },
    modelArrow: { color: colors.spruce, fontFamily: 'MaterialSymbols_400Regular', fontSize: 20 },
    modelMenu: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      elevation: 8,
      left: darkTheme.spacing.content,
      maxHeight: 240,
      position: 'absolute',
      right: darkTheme.spacing.content,
      shadowColor: '#000000',
      shadowOffset: { height: 3, width: 0 },
      shadowOpacity: 0.16,
      shadowRadius: 8,
      top: 50,
    },
    modelOption: {
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 12,
      paddingVertical: 7,
    },
    modelOptionActive: { backgroundColor: colors.spruceSoft },
    modelOptionText: { color: colors.ink, fontSize: 13, lineHeight: 18 },
    modelError: { backgroundColor: colors.berrySoft, paddingHorizontal: 16, paddingVertical: 9 },
    modelErrorText: { color: colors.berry, fontSize: 13, fontWeight: '700' },
    modelLoading: { color: colors.muted, fontSize: 12, marginBottom: 6 },
    messages: { gap: 9, paddingTop: 4 },
    loader: { marginVertical: 28 },
    historyError: {
      backgroundColor: colors.berrySoft,
      borderRadius: darkTheme.radius.input,
      color: colors.berry,
      lineHeight: 20,
      marginVertical: 12,
      padding: 12,
    },
    empty: { color: colors.muted, lineHeight: 21, paddingVertical: 24, textAlign: 'center' },
    message: {
      borderRadius: 18,
      maxWidth: '88%',
      paddingHorizontal: 13,
      paddingVertical: 10,
    },
    userRow: { alignItems: 'flex-end' },
    userMessage: {
      backgroundColor: colors.spruce,
      borderBottomRightRadius: 5,
      maxWidth: '100%',
    },
    agentMessage: {
      alignSelf: 'flex-start',
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderWidth: 1,
      borderBottomLeftRadius: 5,
      minWidth: 0,
      overflow: 'hidden',
    },
    messageText: { color: colors.ink, fontSize: 16, lineHeight: 22 },
    userMessageText: { color: mode === 'dark' ? '#111322' : '#FFFFFF' },
    typingDots: { color: colors.muted, fontSize: 12, letterSpacing: 2 },
    failedRow: { alignItems: 'flex-end', maxWidth: '88%', paddingTop: 4 },
    failedText: { color: colors.berry, fontSize: 12, lineHeight: 17, textAlign: 'right' },
    retry: { alignItems: 'center', flexDirection: 'row', gap: 3, minHeight: 30 },
    retryDisabled: { opacity: 0.5 },
    retryIcon: { color: colors.berry, fontFamily: 'MaterialSymbols_400Regular', fontSize: 17 },
    retryText: { color: colors.berry, fontSize: 12, fontWeight: '700' },
    pendingText: { color: colors.muted, fontSize: 11, paddingTop: 4 },
    memoryCard: {
      backgroundColor: colors.spruceSoft,
      borderRadius: 16,
      marginTop: 14,
      padding: 14,
    },
    memoryLabel: { color: colors.clay, fontSize: 12, fontWeight: '800', letterSpacing: 0.5 },
    memoryText: { color: colors.ink, lineHeight: 20, marginTop: 5 },
    proposalBlock: { marginTop: 4 },
    proposalActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
    confirmMemory: {
      backgroundColor: colors.spruce,
      borderRadius: 10,
      minHeight: 40,
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    confirmMemoryText: { color: colors.white, fontWeight: '800' },
    cancelMemory: {
      borderColor: colors.border,
      borderRadius: 10,
      borderWidth: 1,
      minHeight: 40,
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    cancelMemoryText: { color: colors.muted, fontWeight: '700' },
    choiceCard: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: 14,
      padding: 14,
    },
    choiceLabel: { color: colors.muted, fontSize: 13, fontWeight: '800', marginBottom: 8 },
    choice: {
      borderColor: colors.spruce,
      borderRadius: 12,
      borderWidth: 1,
      justifyContent: 'center',
      marginTop: 8,
      minHeight: 44,
      paddingHorizontal: 12,
    },
    choiceText: { color: colors.spruce, fontWeight: '800', lineHeight: 19 },
    composer: {
      backgroundColor: 'transparent',
      paddingHorizontal: darkTheme.spacing.content,
      paddingTop: 6,
    },
    composerRow: { alignItems: 'flex-end', flexDirection: 'row', gap: 8 },
    composerInput: {
      backgroundColor: colors.white,
      borderColor: colors.border,
      borderRadius: 22,
      borderWidth: 1,
      color: colors.ink,
      elevation: 3,
      flex: 1,
      fontSize: 15,
      height: 44,
      paddingHorizontal: 15,
      paddingVertical: 8,
      shadowColor: '#000000',
      shadowOffset: { height: 2, width: 0 },
      shadowOpacity: 0.12,
      shadowRadius: 5,
    },
    notice: { color: colors.berry, fontSize: 13, lineHeight: 19, marginBottom: 7 },
    accessNotice: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 8 },
  });
}

export function makeMarkdownStyles(colors: ColorTokens) {
  return {
    body: { color: colors.ink, flexShrink: 1, fontSize: 16, lineHeight: 22 },
    paragraph: { color: colors.ink, marginBottom: 10, marginTop: 0 },
    heading1: {
      color: colors.ink,
      fontSize: 24,
      fontWeight: '800' as const,
      lineHeight: 30,
      marginBottom: 8,
      marginTop: 4,
    },
    heading2: {
      color: colors.ink,
      fontSize: 20,
      fontWeight: '800' as const,
      lineHeight: 26,
      marginBottom: 7,
      marginTop: 4,
    },
    heading3: {
      color: colors.ink,
      fontSize: 18,
      fontWeight: '800' as const,
      lineHeight: 24,
      marginBottom: 6,
      marginTop: 4,
    },
    strong: { color: colors.ink, fontWeight: '800' as const },
    em: { color: colors.ink },
    bullet_list: { marginBottom: 8 },
    ordered_list: { marginBottom: 8 },
    list_item: { marginBottom: 4 },
    blockquote: {
      backgroundColor: colors.spruceSoft,
      borderLeftColor: colors.spruce,
      borderLeftWidth: 3,
      color: colors.ink,
      marginVertical: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    code_inline: {
      backgroundColor: colors.linen,
      borderColor: colors.border,
      borderRadius: 4,
      color: colors.clayInk,
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
      paddingHorizontal: 4,
    },
    codeScroll: {
      backgroundColor: colors.linen,
      borderColor: colors.border,
      borderRadius: 10,
      borderWidth: 1,
      marginBottom: 10,
      maxWidth: '100%' as const,
    },
    codeScrollContent: { padding: 12 },
    code_block: {
      color: colors.ink,
      flexShrink: 1,
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
      fontSize: 13,
      lineHeight: 19,
    },
    fence: {
      color: colors.ink,
      flexShrink: 1,
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
      fontSize: 13,
      lineHeight: 19,
    },
    link: { color: colors.spruce, textDecorationLine: 'underline' as const },
    hr: { backgroundColor: colors.border, marginVertical: 12 },
    table: { borderColor: colors.border, maxWidth: '100%' as const },
    th: { backgroundColor: colors.spruceSoft, color: colors.ink, fontWeight: '800' as const },
    td: { borderColor: colors.border, color: colors.ink },
  };
}
